// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertBatchMobileNumbers implements pgx.CopyFromSource.
type iteratorForInsertBatchMobileNumbers struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBatchMobileNumbers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBatchMobileNumbers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertBatchMobileNumbers) Err() error {
	return nil
}

func (q *Queries) InsertBatchMobileNumbers(ctx context.Context, mobileNumber []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"mobile_number"}, []string{"mobile_number"}, &iteratorForInsertBatchMobileNumbers{rows: mobileNumber})
}
