// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: getAllMobileNumbers.sql

package db

import (
	"context"
)

const getAllMobileNumbers = `-- name: GetAllMobileNumbers :many
select mobile_number from mobile_number
`

func (q *Queries) GetAllMobileNumbers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllMobileNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var mobile_number string
		if err := rows.Scan(&mobile_number); err != nil {
			return nil, err
		}
		items = append(items, mobile_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
