// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: getMobileNumer.sql

package db

import (
	"context"
)

const searchMobileNumber = `-- name: SearchMobileNumber :one
select mobile_number from mobile_number where mobile_number = $1 limit 1
`

func (q *Queries) SearchMobileNumber(ctx context.Context, mobileNumber string) (string, error) {
	row := q.db.QueryRow(ctx, searchMobileNumber, mobileNumber)
	var mobile_number string
	err := row.Scan(&mobile_number)
	return mobile_number, err
}
