// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: insertMobileNumber.sql

package db

import (
	"context"
)

const insertMobileNumber = `-- name: InsertMobileNumber :exec
insert into mobile_number (mobile_number) values ($1)
`

func (q *Queries) InsertMobileNumber(ctx context.Context, mobileNumber string) error {
	_, err := q.db.Exec(ctx, insertMobileNumber, mobileNumber)
	return err
}
